//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comp2007_Assignment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Catering
    {
        [Required]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [Required]
        [StringLength(50)]
        public string Email { get; set; }
        [Required]
        [StringLength(50)]
        public string Address { get; set; }
        [Required]
        [StringLength(50)]
        public string Phone { get; set; }
        [Required]
        [Display(Name = "Date"), DataType(DataType.Date)]
        public DateTime? Date { get; set;  }
      //  public Nullable<System.DateTime> Date { get; set; }
        [Required][Range(0,999999999)]
        public Nullable<int> Budget { get; set; }
        [Required]
        [Range(0, 999999999)]
        public Nullable<int> Guests { get; set; }
    }
}
